

source "https://rubygems.org"

gem "net-smtp", "~> 0.3"
gem "pony",     "~> 1.13"
gem "puma",     "~> 6.3"
gem "sinatra", "~> 3.2", ">= 3.2.0"

gem "opentelemetry-sdk", "~> 1.4.1"
gem "opentelemetry-exporter-otlp", "~> 0.26.2"
gem "opentelemetry-instrumentation-all", "~> 0.60.0"
